#!/bin/bash
# Common shell configuration options
# Bailey Forrest <baileycforrest@gmail.com>

# Reload .profile
[ -f $HOME/.profile ] && . $HOME/.profile

# Load configuration files
for config in $XDG_CONFIG_HOME/shell/source/*; do
    . $config
done
unset config

# Set dircolors
if command -v dircolors; then
  DIRCOLORS=$XDG_CONFIG_HOME/shell/dircolors
  test -r $DIRCOLORS && eval "$(dircolors $DIRCOLORS)"
  unset DIRCOLORS
fi

export NVM_DIR="$HOME/.config"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
