#!/bin/bash
# Shell aliases
# Bailey Forrest <baileycforrest@gmail.com>

if [[ "$(uname)" == "Darwin" ]]; then
    alias ls='ls -G'
else
    alias ls='ls --color=auto'
fi

alias usbmount='sudo mount -o gid=users,fmask=113,dmask=002'
alias suvim='sudo vim'
alias l='ls'
alias ll='ls -l'
alias gp='grep --color=auto -n -r'
alias v='vim'
alias xc='xclip -selection clipboard'
alias xv='xclip -selection clipboard -o'
